### ISSUE TITLE
Custom model data does not appear to work in guis

### ISSUE THREAD

**Issue by KermX** [Jsinco/Hoarderv3#1]
Providing an integer for item custom model data throws an exception. When trying to provide it as a string the custom model data is not applied (assumedly because it is expecting a player uuid).

error: https://mclo.gs/TbyMpw6

**Comment by Jsinco** [comment]
Hey, I'll take a look at this when I get a chance. Thanks for letting me know.

**Comment by Jsinco** [comment]
Should be fixed. I'll go ahead and leave this issue open for a while or until I get a response since I didn't hop in-game to test it myself.

**Comment by KermX** [comment]
Seems to be resolved! I appreciate it!
